name: hello-world
on: push
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out Repository
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
